name: dockerbuild

on:
  workflow_dispatch:

jobs:
  devops:
    if: github.event.pull_request.head.repo.full_name == github.repository
    name: DevOps container image build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Build containers
      - name: Build containers
        run: bash devops/build.sh

      # Push containers out to container registries
      - name: Docker Build & Push Action
        uses: mr-smithers-excellent/docker-build-push@v6.3
        with:
          image: tanyastere42/wildbook-test
          registry: docker.io
          username: ${{ secrets.DOCKER_USER_SECRET }}
          password: ${{ secrets.DOCKER_TOKEN_SECRET }}
          dockerfile: ../../devops/wildbook/docker-compose.yml
        
